---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.name}}-ai-build
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: CreateNamespace=true
  labels:
    app.kubernetes.io/instance: ${{values.name}}-ai-build
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: ${{values.name}}-ai-build
    app.kubernetes.io/created-by: backstage
    argocd.argoproj.io/instance: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://${{ parameters.githubServer if parameters.hostType === 'GitHub' else parameters.gitlabServer }}/${{ parameters.repoOwner }}/${{ parameters.repoName }}-gitops.git
    targetRevision: HEAD
    path: ./helm/rag-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.namespace}}-ai
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
