apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${{values.name}}-appproject
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: openshift-gitops
      server: https://kubernetes.default.svc
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
---

