apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${{values.name}}-bootstrap
  namespace: ${{values.argonamespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: ${{values.argonamespace}}
      server: https://kubernetes.default.svc
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
---

