apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.pipeline.serviceAccount }}
  namespace: {{ .Values.pipeline.namespace }}-build
  labels:
    app.kubernetes.io/name: {{ .Values.global.appName }}
    app.kubernetes.io/component: build-pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.global.appName }}-pipeline-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "create", "update", "patch", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["build.openshift.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["image.openshift.io"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.global.appName }}-pipeline-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.global.appName }}-pipeline-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.pipeline.serviceAccount }}
    namespace: {{ .Values.pipeline.namespace }}-build 