apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${{values.name}}-bootstrap
  namespace: janus-argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: janus-argocd
      server: https://kubernetes.default.svc
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "*"
---

