apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id | dump }}
  description: ${{ values.description | dump }}
  namespace: default
  annotations:
    github.com/project-slug: ${{ values.destination | dump }}
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner | dump }}
  providesApis:
    - ${{ values.component_id | dump }}
  consumesApis:
    - ${{ (values.component_id + '-' + values.model_name + '-api') | dump }}
