apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  namespace: default
  annotations:
    github.com/project-slug: ${{values.destination}}
    argocd/app-selector: rht-gitops.com/janus-argocd=${{values.component_id}}-bootstrap
    janus-idp.io/tekton: ${{values.component_id}}
    backstage.io/source-location: url:https://${{values.host}}/${{values.destination}}
    backstage.io/techdocs-ref: url:https://${{values.host}}/${{values.destination}}
    gitlab.com/project-slug: ${{values.destination}}
    quay.io/repository-slug: ${{values.quay_destination | dump}}
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}
  providesApis:
    - ${{values.component_id | dump}}
  consumesApis:
    - ${{values.component_id}}-${{values.model_name}}-api