kind: ConfigMap
apiVersion: v1
metadata:
  name: template
  labels:
    {{- include "llama-serve.labels" . | nindent 4 }}
data:
  tool_chat_template_llama3.2_json.jinja: |-
{{ .Files.Get "files/tool_chat_template_llama3.2_json.jinja" | indent 4}}
  