apiVersion: v1
kind: Secret
metadata:
  name: rag-pipeline-secrets
type: Opaque
stringData:
  MINIO_ENDPOINT: {{ .Values.minio.endpoint }}
  MINIO_ACCESS_KEY: {{ .Values.minio.accessKey }}
  MINIO_SECRET_KEY: {{ .Values.minio.secretKey }}
  LLAMASTACK_BASE_URL: {{ .Values.llamastack.baseUrl }}