stages:
  - build
  - deploy

variables:
  # Using local Quay instance in OpenShift cluster
  REGISTRY: "quay-7vqkm.apps.cluster-7vqkm.7vqkm.sandbox668.opentlc.com"
  # Default Quay username (can be overridden in GitLab CI/CD variables)
  QUAY_USERNAME: "quayadmin"
  IMAGE_NAME: "$REGISTRY/$QUAY_USERNAME/$CI_PROJECT_NAME"
  CONTAINER_IMAGE: "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"

# No services needed - Kaniko builds without Docker daemon

before_script:
  - echo "Registry:" $REGISTRY
  - echo "Image Name:" $IMAGE_NAME
  - echo "Container Image:" $CONTAINER_IMAGE
  - echo "GitOps Webhook:" $GITOPS_WEBHOOK_URL

trigger-build:
  stage: build
  image: curlimages/curl:latest
  script:
    - |
      echo "🚀 Triggering OpenShift Tekton build pipeline..."
      echo "Registry: $REGISTRY"
      echo "Target image: $CONTAINER_IMAGE"
      echo "Source repo: $CI_PROJECT_URL.git"
      echo "Commit SHA: $CI_COMMIT_SHA"

      if [ -n "$GITOPS_WEBHOOK_URL" ]; then
        echo "📡 Triggering GitOps build pipeline..."
        curl -X POST "$GITOPS_WEBHOOK_URL" \
          -H "Content-Type: application/json" \
          -H "X-Gitlab-Event: Push Hook" \
          -d "{
            \"repository\": {
              \"git_http_url\": \"$CI_PROJECT_URL.git\"
            },
            \"after\": \"$CI_COMMIT_SHA\",
            \"ref\": \"refs/heads/$CI_COMMIT_REF_NAME\",
            \"commits\": [{
              \"id\": \"$CI_COMMIT_SHA\",
              \"message\": \"$CI_COMMIT_MESSAGE\"
            }]
          }"
        echo ""
        echo "✅ Build pipeline triggered successfully!"
        echo "   🔧 OpenShift Tekton will build: $CONTAINER_IMAGE"
        echo "   📡 Check OpenShift Developer Console > Pipelines for progress"
        echo "   🎯 ArgoCD will auto-deploy once build completes"
      else
        echo "⚠️  No GITOPS_WEBHOOK_URL configured"
        echo "Please set GITOPS_WEBHOOK_URL to trigger OpenShift builds"
        echo "Expected format: https://your-eventlistener-route/webhook"
      fi
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

trigger-gitops:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - |
      curl -X POST "$GITOPS_WEBHOOK_URL" \
        -H "Content-Type: application/json" \
        -H "X-Gitlab-Event: Push Hook" \
        -d "{
          \"repository\": {
            \"git_http_url\": \"$CI_PROJECT_URL.git\"
          },
          \"after\": \"$CI_COMMIT_SHA\"
        }"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  variables:
    GITOPS_WEBHOOK_URL: $GITOPS_WEBHOOK_URL
