apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    argocd/app-selector: rht-gitops.com/janus-argocd=${{values.name}}-bootstrap
    backstage.io/kubernetes-id: ${{values.name}}
    janus-idp.io/tekton: ${{values.name}}
    backstage.io/source-location: url:https://${{values.host}}/${{values.destination}}
    backstage.io/techdocs-ref: url:https://${{values.host}}/${{values.destination}}
    gitlab.com/project-slug: ${{values.destination}}
  tags:
    - python
    - rag
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}

