apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-secret
  title: Create a Vault secret  
  description: Create secret in HashiCorp Vault
spec:
  owner: dcurran90
  type: service

  parameters:
    - title: Secret Configuration
      required:
        - path
        - key
        - value
      properties:
        path:
          title: Path
          type: string
          description: 'Vault path (mount/secret-name, e.g., "secret/myapp")'
          ui:autofocus: true
        key:
          title: Key
          type: string
          description: Secret key name
        value:
          title: Value
          type: string
          description: Secret value
          ui:widget: password

  steps:
    - id: create-script
      name: Create vault script
      action: roadiehq:utils:fs:write
      input:
        path: ./vault-create.sh
        content: |
          #!/bin/bash
          set -e
          
          # Split path into mount and secret path
          IFS='/' read -ra PATH_PARTS <<< "${{ parameters.path }}"
          MOUNT="${PATH_PARTS[0]}"
          SECRET_PATH="${PATH_PARTS[@]:1}"
          SECRET_PATH=$(IFS=/; echo "${PATH_PARTS[*]:1}")
          
          echo "Creating secret in Vault..."
          echo "Mount: $MOUNT"
          echo "Path: $SECRET_PATH"
          
          # Make API call to Vault (KV v2)
          HTTP_CODE=$(curl -s -w "%{http_code}" -o /tmp/vault-response.json \
            -X POST \
            -H "X-Vault-Token: ${VAULT_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{"data":{"${{ parameters.key }}":"${{ parameters.value }}"}}' \
            "${VAULT_ADDR}/v1/${MOUNT}/data/${SECRET_PATH}")
          
          if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
            echo "✓ Secret created successfully (HTTP $HTTP_CODE)"
            cat /tmp/vault-response.json
          else
            echo "✗ Failed to create secret (HTTP $HTTP_CODE)"
            cat /tmp/vault-response.json
            exit 1
          fi

    - id: make-executable
      name: Make script executable
      action: roadiehq:utils:fs:execute
      input:
        command: chmod
        args:
          - '+x'
          - ./vault-create.sh

    - id: create-secret
      name: Execute vault creation
      action: roadiehq:utils:fs:execute
      input:
        command: bash
        args:
          - ./vault-create.sh

  output:
    text:
      - title: 'Secret Created'
        content: |
          ✓ Secret successfully created in Vault
          
          **Location:** `${{ parameters.path }}`
          **Key:** `${{ parameters.key }}`
          
          **Output:**
          ```
          ${{ steps['create-secret'].output.stdout }}
          ```
